PizzaMenuTitle = 'Dominos Menu'
PizzaInfoNameEntry = 'Enter Your Contact'
PizzaInfoAddressEntry = 'Enter Your Address'
PizzaInfoCardEntry = 'Enter Your Payment'
PizzaInfoIncorrectEntry = 'Please Try Again'
PizzaInfoSubmit = 'Submit'
PizzaEntryName = ('First Name', 'Last Name', 'Email Address', 'Phone Number')
PizzaEntryAddress = ('Street Address', 'City', 'State', 'ZIP Code')
PizzaEntryCard = ('Card Number', 'Expiration Date', 'Security Code', 'ZIP Code')
PizzaButtons = ('Browse Menu', 'Change Info', 'Close')
PizzaCouponTitle = 'Daily Deals!'
PizzaNoCoupon = 'Looks like there are no deals today. Check back later!'
PizzaInfoSearch = 'Search Products'
PizzaInfoSelect = 'Add To Cart'
PizzaInfoCheckout = 'Checkout'
PizzaPlaceOrder = 'Place Order'
PizzaRemoveCart = 'Remove From Cart'
PizzaTotals = 'Subtotal: ${}\nDelivery: ${}\nSales Tax: ${}\nTotal: ${}'
PizzaOrderPlaced = 'Ordered placed successfully!\nYour card has been charged {}.\n\nTime to celebrate, pizza is coming!'
